### ISSUE TITLE
Mac OS X: Errorjava.lang.NoClassDefFoundError: jssc/SerialPortEventListener

### ISSUE THREAD

**Issue by Dradnats** [electronicadivertida/scratch2LittleBits#2]
Hi,

Thanks for you work on this extension.  

Had an issue during the installing the jar file, not sure if something is missing in the classpath.

Info: java version "1.6.0_65", Mac OS X 10.10

Appreciate any assistance.

Thanks,

Martin

java -jar scratch2LittleBits.jar 
java.lang.NoClassDefFoundError: jssc/SerialPortEventListener
	at scratch2littlebits.Scratch2LittleBits.conectarArduino(Scratch2LittleBits.java:84)
	at scratch2littlebits.Scratch2LittleBits$5.run(Scratch2LittleBits.java:228)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.ClassNotFoundException: jssc.SerialPortEventListener
	at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	... 16 more

**Comment by electronicadivertida** [comment]
Files may be missing, along with "scratch2LittleBits.jar" must be the "lib" directory, ie the directory structure is as follows:

scratch2LittleBits.jar
lib / jsonOrg.jar
lib / jssc.jar

regards

**Comment by Dradnats** [comment]
Hi,
Issue solved.
Just for clarification, is there a better way to download all files at once, instead of each file at a time?
Thanks,
Martin
